"""Add url column to jobs table

Revision ID: a6305d424e21
Revises: 4e3be38ebaa3
Create Date: 2024-09-28 17:30:52.499102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6305d424e21'
down_revision: Union[str, None] = '4e3be38ebaa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'url')
    # ### end Alembic commands ###
